# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 350)
        MainWindow.setMinimumSize(QtCore.QSize(300, 350))
        MainWindow.setMaximumSize(QtCore.QSize(300, 350))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.voting_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.voting_label.setGeometry(QtCore.QRect(80, 20, 151, 16))
        self.voting_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.voting_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.voting_label.setObjectName("voting_label")
        self.ID_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ID_label.setGeometry(QtCore.QRect(50, 50, 47, 14))
        self.ID_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ID_label.setObjectName("ID_label")
        self.cand_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.cand_label.setGeometry(QtCore.QRect(90, 100, 121, 16))
        self.cand_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cand_label.setObjectName("cand_label")
        self.snoopy_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.snoopy_button.setGeometry(QtCore.QRect(100, 130, 111, 18))
        self.snoopy_button.setObjectName("snoopy_button")
        self.joe_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.joe_button.setGeometry(QtCore.QRect(100, 150, 83, 18))
        self.joe_button.setObjectName("joe_button")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(110, 190, 75, 23))
        self.submit_button.setObjectName("submit_button")
        self.id_box = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id_box.setGeometry(QtCore.QRect(100, 50, 113, 20))
        self.id_box.setObjectName("id_box")
        self.output_box = QtWidgets.QLabel(parent=self.centralwidget)
        self.output_box.setGeometry(QtCore.QRect(50, 230, 191, 61))
        self.output_box.setText("")
        self.output_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_box.setObjectName("output_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Final Project GUI"))
        self.voting_label.setText(_translate("MainWindow", "VOTING APPLICATION"))
        self.ID_label.setText(_translate("MainWindow", "ID"))
        self.cand_label.setText(_translate("MainWindow", "CANDIDATES"))
        self.snoopy_button.setText(_translate("MainWindow", "Snoopy"))
        self.joe_button.setText(_translate("MainWindow", "Joe Cool"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
